### ISSUE TITLE
SVG of k8s-logo is not output correctly.

### ISSUE THREAD

**Issue by rnakamine** [k1LoW/ndiag#105]
When I try to use the icon for k8s-logo, it does not display correctly.

I have reproduced the problem by following the steps below.

```sh
$ ndiag --version
ndiag version 0.14.4
```

1. Get the icon of k8s

```sh
$ ndiag fetch-icons k8s
Fetching icons from https://github.com/kubernetes/community/archive/master.zip ...
Fetching icons from https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo_with_border.svg ...
73 icons fetched
Done.
```

2. Generate documentation
```sh
$ ndiag doc -c ndiag.yml --rm-dist
```

The config file used is as follows.
```yaml
---
name: Test
docPath: docs/arch
nodes:
  -
    name: Kubernetes
    components:
      - CLUSTER-1?icon=k8s-logo
```

Output:
<img width="164" alt="image" src="https://github.com/k1LoW/ndiag/assets/34146717/26ea43a3-69a9-4a43-b554-c13fc87d976c">

**Comment by rnakamine** [comment]
This problem seems to occur only with k8s-logo in k8s icons.

By the way, other k8s icons and AWS display correctly.

```yaml
---
name: Test
docPath: docs/arch
nodes:
  -
    name: aws
    components:
      - foo?icon=aws-ec2

  -
    name: k8s
    components:
      - bar?icon=k8s-resources-pod
```

Output:
<img width="243" alt="image" src="https://github.com/k1LoW/ndiag/assets/34146717/473df77a-62e1-4413-b972-9db0d962b68b">
